overrides:
  '@babel/core@<=7.29.0': ^7.29.1
  picomatch: ^4.0.4
  esbuild@>=0.27.3 <0.28.1: ^0.28.1

allowBuilds:
  '@parcel/watcher': true
  core-js: true
  esbuild: true
  inferno: true
  lmdb: true
  msgpackr-extract: true

minimumReleaseAgeExclude:
  - piscina@5.1.5
