name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - name: Get sources
      uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Restore npm cache
      uses: actions/cache@v3
      with:
        path: ./node_modules
        key: ${{ runner.os }}-node-modules

    - name: Run npm install
      run: npm install --no-audit --no-fund

    - name: Install Internal Package
      uses: DevExpress/github-actions/install-internal-package@main

    - name: Build
      run: npm run build -- --configuration=production --base-href https://devexpress.github.io/devextreme-angular-template/

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@ba1486788b0490a235422264426c45848eac35c6
      with:
        branch: gh-pages
        folder: dist/DevExtreme-App
        target-folder: .
